//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracHasar.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracHasarBilgisi
    {
        public int ID { get; set; }
        public Nullable<int> MotorNo { get; set; }
        public string PlakaNo { get; set; }
        public string ListeTipi { get; set; }
        public string Acente { get; set; }
        public string Sube { get; set; }
        public string HasarBolgesi { get; set; }
        public string HasarDerecesi { get; set; }
        public string KazaSebebi { get; set; }
        public Nullable<System.DateTime> KazaTarihi { get; set; }
    
        public virtual MusteriBilgisi MusteriBilgisi { get; set; }
    }
}
