//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracHasar.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int KullanıcıID { get; set; }
        public string Kullanıcıİsmi { get; set; }
        public string Sifre { get; set; }

        public string GirisErrorMessage { get; set; }
    }
}
