//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracHasar.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBilgisi
    {
        public int ID { get; set; }
        public string MotorNo { get; set; }
        public string MusteriNo { get; set; }
        public string AdSoyad { get; set; }
        public string TelNo { get; set; }
    
        public virtual AracHasarBilgisi AracHasarBilgisi { get; set; }
    }
}
